<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
=======
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
>>>>>>> 7bf8281 (Add likes, comments, shares, search, and logout functionality with fixes)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
<<<<<<< HEAD
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
=======
      // Configuration WEB
      return const FirebaseOptions(
        apiKey: 'AIzaSyBpdWUavr3jZYkxgrhZm0f27oMakZYe-fs', // Clé extraite du JSON
        appId: '1:870965217564:web:YOUR_WEB_APP_ID', // ID Web toujours manquant, on garde le placeholder pour l'instant ou on utilise celle d'Android faute de mieux (risque d'erreur sur Web)
        messagingSenderId: '870965217564',
        projectId: 'sojatconnect',
        authDomain: 'sojatconnect.firebaseapp.com',
        storageBucket: 'sojatconnect.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Configuration ANDROID
        return const FirebaseOptions(
          apiKey: 'AIzaSyBpdWUavr3jZYkxgrhZm0f27oMakZYe-fs', // Clé extraite du JSON
          appId: '1:870965217564:android:6ca316a14dd9b5251912d9',
          messagingSenderId: '870965217564',
          projectId: 'sojatconnect',
          storageBucket: 'sojatconnect.firebasestorage.app',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> 7bf8281 (Add likes, comments, shares, search, and logout functionality with fixes)
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
<<<<<<< HEAD

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7IyslsAldb2SwYz9o0OiE_13deL2B-w',
    appId: '1:870965217564:web:07ac70b3054cc6051912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    authDomain: 'sojatconnect.firebaseapp.com',
    storageBucket: 'sojatconnect.firebasestorage.app',
    measurementId: 'G-J19CHFX9BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdWUavr3jZYkxgrhZm0f27oMakZYe-fs',
    appId: '1:870965217564:android:6ca316a14dd9b5251912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcd4UlAxlZqtkHk8nxQOoxdCQKcOtHEg',
    appId: '1:870965217564:ios:c5f731c8546bdb6e1912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcd4UlAxlZqtkHk8nxQOoxdCQKcOtHEg',
    appId: '1:870965217564:ios:c5f731c8546bdb6e1912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS7IyslsAldb2SwYz9o0OiE_13deL2B-w',
    appId: '1:870965217564:web:c9f489e2d387e2411912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    authDomain: 'sojatconnect.firebaseapp.com',
    storageBucket: 'sojatconnect.firebasestorage.app',
    measurementId: 'G-S1EZGTDC27',
  );
=======
>>>>>>> 7bf8281 (Add likes, comments, shares, search, and logout functionality with fixes)
}
