// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7IyslsAldb2SwYz9o0OiE_13deL2B-w',
    appId: '1:870965217564:web:07ac70b3054cc6051912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    authDomain: 'sojatconnect.firebaseapp.com',
    storageBucket: 'sojatconnect.firebasestorage.app',
    measurementId: 'G-J19CHFX9BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdWUavr3jZYkxgrhZm0f27oMakZYe-fs',
    appId: '1:870965217564:android:6ca316a14dd9b5251912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcd4UlAxlZqtkHk8nxQOoxdCQKcOtHEg',
    appId: '1:870965217564:ios:c5f731c8546bdb6e1912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcd4UlAxlZqtkHk8nxQOoxdCQKcOtHEg',
    appId: '1:870965217564:ios:c5f731c8546bdb6e1912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    storageBucket: 'sojatconnect.firebasestorage.app',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS7IyslsAldb2SwYz9o0OiE_13deL2B-w',
    appId: '1:870965217564:web:c9f489e2d387e2411912d9',
    messagingSenderId: '870965217564',
    projectId: 'sojatconnect',
    authDomain: 'sojatconnect.firebaseapp.com',
    storageBucket: 'sojatconnect.firebasestorage.app',
    measurementId: 'G-S1EZGTDC27',
  );
}
